server.port=18080
server.tomcat.threads.max=200
spring.main.allow-circular-references=true

spring.messages.basename=i18n/message

app.myvar1=var1
app.myvara=vara

mybatis.mapper-locations=classpath:mapper/**/*.xml

# hikari datasource properties
spring.datasource.hikari.maximum-pool-size=3

# db inner common properties
spring.datasource.username=local_debug_root
spring.datasource.password=local_debug_pwd

# db customized common properties
app.db.sql-locations=db/common/v1/mysql/table_group_ddl.sql,db/common/v1/mysql/data_init_dml.sql,db/common/v1/mysql/procedure_group_ddl.sql
app.db.name=local_test_db
# options: mariadb4j, h2, or external
app.db.type=external

# External mariadb4j
spring.datasource.url=jdbc:mysql://localhost:3306/${app.db.name}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# External mariadb4j
#spring.datasource.url=jdbc:mariadb://localhost:3306/${app.db.name}
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# H2
#spring.datasource.url=jdbc:h2:mem:${app.db.name};DB_CLOSE_DELAY=-1;MODE=MySQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=true

# MariaDB4j
#app.db.mariadb4j.port=13306
##memory: app.db.mariadb4j.data-dir=./target/mariadb4j
#app.db.mariadb4j.args=--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#spring.datasource.url=jdbc:mariadb://localhost:${app.db.mariadb4j.port}/${app.db.name}
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

